services:
  db:
    image: mysql:9.3
    restart: always
    environment:
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'hyperf'
    volumes:
      - 'db_data:/var/lib/mysql'
    networks:
      - hyperf-skeleton
    ports:
      - "3306:3306"

volumes:
  db_data:
    driver: local

networks:
  hyperf-skeleton:
    driver: bridge
